### PR TITLE
added favicon to fix the chrome logo

### LINKED ISSUE #28: Add logo to chrome tab
**When/where was it happening:**
On chrome on linux
**What is happening, step by step:**
React logo on the tab
**Can it be reproduced? If yes, how?:**
yes

### PR DESCRIPTION
**Pull request by mAkeddar**
**Related to:** Prs: # , Github issues: # :

Fixes #28 
<h2>Changes proposed in this pull request:</h2>
Added the right fav icon to public folder

### CODE REVIEW

File: portato/src/Pages/Sender/Summary.tsx [hunk 1]
```diff
@@ -34,6 +34,7 @@ const Summary: React.FC = () => {
     setIsModalVisible(false);
   };
   const objecInfo = useSelector((state: IObjectInfo) => state);
+  console.log(objecInfo);
```
Comment (hugo2410) [inline portato/src/Pages/Sender/Summary.tsx:37]:
```suggestion

```

**Review by hugo2410 — APPROVED** [review]
