### PR TITLE
fix flickering after signin

### LINKED ISSUE #31: Add loading screen after sign in to avoid flickering
**How to file an issue:**
* Fill in info below.
* If more information becomes available please update fields.
* Please always add the issue to the SW bug board (project) for prioritization.

**When/where was it happening:**

**What is happening, step by step:**

**Can it be reproduced? If yes, how?:**

**Plots/screenshots/links to datasets:**

### PR DESCRIPTION
**Pull request by mAkeddar**
**Related to:** Prs: # , Github issues: # :

Fixes #31 

<h2>Changes proposed in this pull request:</h2>
 The OnAuthStateChanged Observer is triggered asynchronously so there is a delay sometime.
My solution: Hide the UI until OnAuthStateChanged changed the user state.

### CODE REVIEW

**Comment by hugo2410** [comment]
@mAkeddar it improves on the flickering side, the sign in button switches from confirm to sign in to confirm but i think as a v0 thats fine

File: portato/src/Components/AuthWrapper.tsx [hunk 1]
```diff
@@ -34,24 +34,17 @@ const AuthWrapper: React.FC<AuthWrapperProps> = ({ Component }) => {
...
-          backgroundColor: "#2897FF",
+          backgroundColor: "#ffffff",
         }}
       >
         <Spin size="large" />
       </div>
     );
-  }
+  } else {
+    console.log("Rendering user in else:", user); // Added console log
```
Comment (hugo2410) [inline portato/src/Components/AuthWrapper.tsx:44]:
```suggestion
```

File: portato/src/Components/ProfileContent.tsx [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+
+function ProfileContent() {
+  const [user, setUser] = useState<User | null>(null);
+  console.log("COOOOOOON");
+  const [display, setDisplay] = useState("none");
+  const navigate = useNavigate();
+  useEffect(() => {
+    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
+      if (currentUser) {
+        console.log("User signed in:", currentUser); // Added console log
```
Comment (hugo2410) [inline portato/src/Components/ProfileContent.tsx:25]:
```suggestion
```

File: portato/src/Components/ProfileContent.tsx [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+        setUser(currentUser);
+        setDisplay("");
+      } else {
+        console.log("User signed out"); // Added console log
```
Comment (hugo2410) [inline portato/src/Components/ProfileContent.tsx:29]:
```suggestion
```

**Review by hugo2410 — APPROVED** [review]
